### ISSUE TITLE
방문자수!

### ISSUE THREAD

**Issue by lovelyhwado** [TalentDonationChallenge/BreatheGym#9]
`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '8ee4181982d195bafa806f6abed2ef59' for key 'PRIMARY'' in /Users/Gayeon/Dropbox/BreatheGym/framework/model/visitCountDB.php:39 Stack trace: #0 /Users/Gayeon/Dropbox/BreatheGym/framework/model/visitCountDB.php(39): PDOStatement->execute(Array) #1 /Users/Gayeon/Dropbox/BreatheGym/framework/framework.php(36): VisitCountDB::insertVisitRecord('8ee4181982d195b...', '2015-10-08') #2 /Users/Gayeon/Dropbox/BreatheGym/index.php(2): require_once('/Users/Gayeon/D...') #3 {main} thrown in /Users/Gayeon/Dropbox/BreatheGym/framework/model/visitCountDB.php on line 39`

이런 에러가 납니다!

**Comment by Burningsweetpotato** [comment]
왜죠

**Comment by Burningsweetpotato** [comment]
원인 발견해서 수정하여서 업뎃했어요!
